# Generated by Django 3.1.5 on 2023-04-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20230401_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question1',
            name='answer1',
            field=models.CharField(choices=[('0-6 months', '0-6 months'), ('6-12 months', '6-12 months')], max_length=264, null=True),
        ),
    ]
