# Generated by Django 3.1.5 on 2023-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20230401_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='question1',
            name='answer2',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Retail', 'Retail'), ('Other', 'Other')], max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='question1',
            name='answer3',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Frontend and Backend', 'Frontend and Backend')], max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='question1',
            name='answer4',
            field=models.CharField(choices=[('React', 'React'), ('Angular', 'Angular'), ('Vue', 'Vue'), ('Other', 'Other')], max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='question1',
            name='answer5',
            field=models.CharField(choices=[('NPM/Yarn', 'NPM/Yarn'), ('Webpack', 'Webpack'), ('Grunt/Gulp', 'Grunt/Gulp'), ('Babel', 'Babel')], max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='question1',
            name='answer6',
            field=models.CharField(choices=[('Node.js', 'Node.js'), ('Django', 'Django'), ('Ruby on Rails', 'Ruby on Rails'), ('Spring Boot', 'Spring Boot'), ('ASP.NET', 'ASP.NET'), ('Other', 'Other')], max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='question1',
            name='answer7',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('C#', 'C#'), ('Other', 'Other')], max_length=264, null=True),
        ),
    ]
