# Generated by Django 3.1.5 on 2023-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20230401_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='newemployee',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
