# Generated by Django 3.1.5 on 2023-04-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_newemployee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldemployee',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
