# Generated by Django 3.1.5 on 2023-04-02 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0006_oldemployee_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(choices=[('1-3 years', '1-3 years'), ('3-5 years', '3-5 years'), ('5-10 years', '5-10 years'), ('More than 10 years', 'More than 10 years')], max_length=264, null=True)),
                ('answer2', models.CharField(choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Retail', 'Retail'), ('Other', 'Other')], max_length=264, null=True)),
                ('answer3', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Frontend and Backend', 'Frontend and Backend')], max_length=264, null=True)),
                ('answer4', models.CharField(choices=[('React', 'React'), ('Angular', 'Angular'), ('Vue', 'Vue'), ('Other', 'Other')], max_length=264, null=True)),
                ('answer5', models.CharField(choices=[('NPM/Yarn', 'NPM/Yarn'), ('Webpack', 'Webpack'), ('Grunt/Gulp', 'Grunt/Gulp'), ('Babel', 'Babel')], max_length=264, null=True)),
                ('answer6', models.CharField(choices=[('Node.js', 'Node.js'), ('Django', 'Django'), ('Ruby on Rails', 'Ruby on Rails'), ('Spring Boot', 'Spring Boot'), ('ASP.NET', 'ASP.NET'), ('Other', 'Other')], max_length=264, null=True)),
                ('answer7', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('C#', 'C#'), ('Other', 'Other')], max_length=264, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
